name: Java Code Check for explosion

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Checking for stupidity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'    
          
      # Step 3: Static analysis (using Checkstyle)
      - name: Run Checkstyle (optional)
        run: |
          curl -LJO https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.0/checkstyle-10.12.0-all.jar
          java -jar checkstyle-10.12.0-all.jar -c /google_checks.xml $(find . -name "*.java")
