name: Java Code Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Adoptium's Temurin distribution
          java-version: '17'     # Adjust Java version as needed

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install dependencies and build project
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      # Step 5: Run tests
      - name: Run tests
        run: mvn test --no-transfer-progress

      # Step 6: Analyze code quality (optional, using SpotBugs)
      - name: Run SpotBugs (optional)
        run: mvn spotbugs:check
